import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen flex flex-col">
          {/* Toaster */}

          {/* Header */}
          <header className="border-b sticky bg-white">
            <Header />
          </header>

          <main className="bg-[#F4F2ED] flex-1">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
